parameters:
  data: '/rds/general/user/hf721/home/RNA_FOLDING/DATA/Toehold_Dataset_Final_2019-10-23.csv'
  in_cols: ['seq_SwitchON_GFP']
  out_cols: ['ON']
  qc_level: 1.1
  scaler_init: True
  epochs: 200
  filters: [128, 64, 32]
  optimizer: 'adam'
  loss_fn: 'mse'
  learning_rate: 0.001
  weight_decay: 0.000005
  epsilon: 0.00000001
  dropout: 0.3
  batch_size: 32
  num_workers: 4
  seed: 123
