<<<<<<< HEAD
program: MLP_1D_wandb.py
=======
program: test_wandb.py
>>>>>>> 4834e1470b3fede696f87b15b91838a259fa34e2
method: grid
metric:
  name: R2_metric
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 5
parameters:
  in_cols:
<<<<<<< HEAD
    value: ['switch']
  out_cols:
    value: ['ON', 'OFF']
  qc_level:
    value: 1.1
  scaler_init:
    value: True
  epochs:
    value: 200
  filters:
    value: [128, 64, 32]
  optimizer:
    value: 'adam'
  loss_fn:
    value: 'mse'
  learning_rate:
    value: 0.001
=======
    value: 'seq_SwitchON_GFP'
  out_cols:
    value: ['ON', 'OFF']
  qc_level:
    values: [0.7, 1.1]
  scaler_init:
    values: [True, False]
  epochs:
    value: 200
  filters:
    values: [[128, 64, 32, 16], [256, 128, 64, 32, 16]]
  optimizer:
    value: 'adam'
  loss_fn:
    value: 'mae'
  learning_rate:
    values: [0.00075, 0.001]
>>>>>>> 4834e1470b3fede696f87b15b91838a259fa34e2
  weight_decay:
    value: 0.0001
  epsilon:
    value: 0.001
  dropout:
<<<<<<< HEAD
    value: 0.3
=======
    values: [0.01, 0.1]
>>>>>>> 4834e1470b3fede696f87b15b91838a259fa34e2
  batch_size:
    value: 64
