program: 02_LSTM_1D.py
method: grid
metric:
  name: R2_metric
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 5
parameters:
  in_cols:
    value: 'seq_SwitchON_GFP'
  out_cols:
    value: ['ON', 'OFF']
  qc_level:
    value: 1.1
  scaler_init:
    value: True
  epochs:
    value: 200
  filters:
    value: [128]
  optimizer:
    value: 'adam'
  loss_fn:
    value: 'mse'
  learning_rate:
    value: 0.001
  weight_decay:
    value: 0.0001
  epsilon:
    value: 0.001
  dropout:
    value: 0.1
  batch_size:
    value: 64
